name: dart_interpreter
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: '>=2.18.0-58.0.dev <3.0.0'

dependencies:
  args: ^2.3.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
